# NOTE: This docker-compose.yml is meant to be just an example of how
# you could accomplish this on your own. It is not intended to work in
# all use-cases and must be adapted to fit your needs. This is merely
# a guideline.

# See docs.getsentry.com/on-premise/server/ for full
# instructions

version: '2'
services:
  base:
    build: .
    environment:
      # Run `docker-compose run web config generate-secret-key`
      # to get the SENTRY_SECRET_KEY value.
      # SENTRY_SECRET_KEY: ''
      SENTRY_MEMCACHED_HOST: memcached
      SENTRY_REDIS_HOST: redis
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_EMAIL_HOST: smtp
    volumes:
      - ./data/sentry:/var/lib/sentry/files
      - ./sentry.conf.py:/etc/sentry/sentry.conf.py

  smtp:
    image: tianon/exim4

  memcached:
    image: memcached:1.4

  redis:
    image: redis:3.2-alpine

  postgres:
    image: postgres:9.5
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  web:
    extends: base
    links:
      - redis
      - postgres
      - memcached
      - smtp
    ports:
      - '9000:9000'
    environment: 
      VIRTUAL_HOST: 'example.com'
      VIRTUAL_PORT: 9000

  cron:
    extends: base
    command: run cron
    links:
      - redis
      - postgres
      - memcached
      - smtp

  worker:
    extends: base
    command: run worker
    links:
      - redis
      - postgres
      - memcached
      - smtp

  nginx:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/nginx/vhosts.d
      - /etc/nginx/conf.d
      - /usr/share/nginx/html
      - /data/certs:/etc/nginx/certs:ro
    environment:
      LETSENCRYPT_EMAIL: 'info@example.com'
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    links: 
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /data/certs:/etc/nginx/certs:rw
    volumes_from:
      - nginx
    environment:
      LETSENCRYPT_HOST: 'example.com'
      LETSENCRYPT_EMAIL: 'admin@example.com'
    restart: always
    
